export const MIN_COMMAND_MATRIX = [
  {
    id: "linux_apt_update",
    label: "Linux: apt update",
    description: "Refreshes the local package index on Ubuntu/Debian.",
    family: "linux_package_management",
    platform: "linux",
    shell: "bash",
    shellOptions: ["bash", "sh"],
    runAsSystem: true,
    command: "apt-get update",
    tags: ["linux", "ubuntu", "debian", "apt", "update"],
  },
  {
    id: "linux_apt_upgrade",
    label: "Linux: apt upgrade -y",
    description: "Installs all currently available package upgrades.",
    family: "linux_package_management",
    platform: "linux",
    shell: "bash",
    shellOptions: ["bash", "sh"],
    runAsSystem: true,
    command: "apt-get upgrade -y",
    tags: ["linux", "ubuntu", "debian", "apt", "upgrade"],
  },
  {
    id: "linux_apt_full_upgrade",
    label: "Linux: apt full-upgrade -y",
    description: "Upgrades packages and resolves dependency changes.",
    family: "linux_package_management",
    platform: "linux",
    shell: "bash",
    shellOptions: ["bash", "sh"],
    runAsSystem: true,
    command: "apt-get full-upgrade -y",
    tags: ["linux", "ubuntu", "debian", "apt", "full-upgrade"],
  },
  {
    id: "linux_apt_autoremove",
    label: "Linux: apt autoremove -y",
    description: "Removes obsolete dependency packages and old kernels.",
    family: "linux_package_management",
    platform: "linux",
    shell: "bash",
    shellOptions: ["bash", "sh"],
    runAsSystem: true,
    command: "apt-get autoremove -y",
    tags: ["linux", "ubuntu", "debian", "apt", "autoremove"],
  },
  {
    id: "linux_dnf_upgrade",
    label: "Linux: dnf upgrade -y",
    description: "Standard upgrade command for Fedora/RHEL/CentOS streams.",
    family: "linux_package_management",
    platform: "linux",
    shell: "bash",
    shellOptions: ["bash", "sh"],
    runAsSystem: true,
    command: "dnf upgrade -y",
    tags: ["linux", "rhel", "fedora", "centos", "dnf", "upgrade"],
  },
  {
    id: "linux_yum_update",
    label: "Linux: yum update -y",
    description: "Legacy package update command for older RHEL/CentOS hosts.",
    family: "linux_package_management",
    platform: "linux",
    shell: "bash",
    shellOptions: ["bash", "sh"],
    runAsSystem: true,
    command: "yum update -y",
    tags: ["linux", "rhel", "centos", "yum", "update"],
  },
  {
    id: "linux_pacman_update",
    label: "Linux: pacman -Syu --noconfirm",
    description: "Full system sync and update command for Arch Linux.",
    family: "linux_package_management",
    platform: "linux",
    shell: "bash",
    shellOptions: ["bash", "sh"],
    runAsSystem: true,
    command: "pacman -Syu --noconfirm",
    tags: ["linux", "arch", "pacman", "update"],
  },
  {
    id: "linux_zypper_update",
    label: "Linux: zypper update -y",
    description: "Standard update command for openSUSE/SLES endpoints.",
    family: "linux_package_management",
    platform: "linux",
    shell: "bash",
    shellOptions: ["bash", "sh"],
    runAsSystem: true,
    command: "zypper update -y",
    tags: ["linux", "opensuse", "sles", "zypper", "update"],
  },
  {
    id: "linux_list_upgradable",
    label: "Linux: apt list --upgradable",
    description: "Lists packages with newer versions available.",
    family: "linux_package_management",
    platform: "linux",
    shell: "bash",
    shellOptions: ["bash", "sh"],
    runAsSystem: false,
    command: "apt list --upgradable",
    tags: ["linux", "apt", "list", "upgradable"],
  },
  {
    id: "linux_kernel_version",
    label: "Linux: uname -r",
    description: "Reports current kernel version for reboot validation.",
    family: "linux_package_management",
    platform: "linux",
    shell: "bash",
    shellOptions: ["bash", "sh"],
    runAsSystem: false,
    command: "uname -r",
    tags: ["linux", "kernel", "uname", "reboot-check"],
  },
  {
    id: "linux_patch_cycle",
    label: "Linux: apt update + upgrade + autoremove",
    description: "One-shot Linux patch cycle for Ubuntu/Debian package maintenance.",
    family: "linux_package_management",
    platform: "linux",
    shell: "bash",
    shellOptions: ["bash", "sh"],
    runAsSystem: true,
    command: "apt-get update && apt-get upgrade -y && apt-get autoremove -y",
    tags: ["linux", "apt", "patch", "combined"],
  },
  {
    id: "windows_usoclient_scan",
    label: "Windows: UsoClient StartScan",
    description: "Triggers Windows Update background scan.",
    family: "windows_os_native",
    platform: "windows",
    shell: "powershell",
    shellOptions: ["powershell", "cmd"],
    runAsSystem: true,
    command: "UsoClient StartScan",
    tags: ["windows", "usoclient", "scan", "update"],
  },
  {
    id: "windows_usoclient_download",
    label: "Windows: UsoClient StartDownload",
    description: "Forces download of pending Windows updates.",
    family: "windows_os_native",
    platform: "windows",
    shell: "powershell",
    shellOptions: ["powershell", "cmd"],
    runAsSystem: true,
    command: "UsoClient StartDownload",
    tags: ["windows", "usoclient", "download", "update"],
  },
  {
    id: "windows_usoclient_install",
    label: "Windows: UsoClient StartInstall",
    description: "Installs downloaded Windows updates.",
    family: "windows_os_native",
    platform: "windows",
    shell: "powershell",
    shellOptions: ["powershell", "cmd"],
    runAsSystem: true,
    command: "UsoClient StartInstall",
    tags: ["windows", "usoclient", "install", "update"],
  },
  {
    id: "windows_usoclient_restart",
    label: "Windows: UsoClient RestartDevice",
    description: "Reboots endpoint to complete pending update changes.",
    family: "windows_os_native",
    platform: "windows",
    shell: "powershell",
    shellOptions: ["powershell", "cmd"],
    runAsSystem: true,
    command: "UsoClient RestartDevice",
    tags: ["windows", "usoclient", "restart", "reboot"],
  },
  {
    id: "windows_wuauclt_detectnow",
    label: "Windows: wuauclt /detectnow",
    description: "Legacy command to force Windows Update check-in.",
    family: "windows_os_native",
    platform: "windows",
    shell: "powershell",
    shellOptions: ["powershell", "cmd"],
    runAsSystem: true,
    command: "wuauclt /detectnow",
    tags: ["windows", "wuauclt", "detectnow", "legacy"],
  },
  {
    id: "windows_wuauclt_updatenow",
    label: "Windows: wuauclt /updatenow",
    description: "Legacy command to force immediate update install.",
    family: "windows_os_native",
    platform: "windows",
    shell: "powershell",
    shellOptions: ["powershell", "cmd"],
    runAsSystem: true,
    command: "wuauclt /updatenow",
    tags: ["windows", "wuauclt", "updatenow", "legacy"],
  },
  {
    id: "windows_get_hotfix",
    label: "Windows PS: Get-Hotfix",
    description: "Lists installed Windows updates and KB entries.",
    family: "windows_os_native",
    platform: "windows",
    shell: "powershell",
    shellOptions: ["powershell"],
    runAsSystem: false,
    command: "Get-Hotfix",
    tags: ["windows", "powershell", "hotfix", "kb"],
  },
  {
    id: "windows_get_wu_reboot_status",
    label: "Windows PS: Get-WURebootStatus",
    description: "Checks whether update reboot is pending.",
    family: "windows_os_native",
    platform: "windows",
    shell: "powershell",
    shellOptions: ["powershell"],
    runAsSystem: false,
    command: "Get-WURebootStatus",
    tags: ["windows", "powershell", "reboot", "windowsupdate"],
  },
  {
    id: "windows_get_windows_update",
    label: "Windows PS: Get-WindowsUpdate -MicrosoftUpdate",
    description: "Lists pending updates via PSWindowsUpdate.",
    family: "windows_os_native",
    platform: "windows",
    shell: "powershell",
    shellOptions: ["powershell"],
    runAsSystem: false,
    command: "Get-WindowsUpdate -MicrosoftUpdate",
    tags: ["windows", "powershell", "windowsupdate", "scan"],
  },
  {
    id: "windows_install_windows_update",
    label: "Windows PS: Install-WindowsUpdate -AcceptAll",
    description: "Automates update download and install via PSWindowsUpdate.",
    family: "windows_os_native",
    platform: "windows",
    shell: "powershell",
    shellOptions: ["powershell"],
    runAsSystem: true,
    command: "Install-WindowsUpdate -MicrosoftUpdate -AcceptAll -AutoReboot",
    tags: ["windows", "powershell", "windowsupdate", "install"],
  },
  {
    id: "windows_get_wu_history",
    label: "Windows PS: Get-WUHistory",
    description: "Shows historical update install events.",
    family: "windows_os_native",
    platform: "windows",
    shell: "powershell",
    shellOptions: ["powershell"],
    runAsSystem: false,
    command: "Get-WUHistory",
    tags: ["windows", "powershell", "windowsupdate", "history"],
  },
  {
    id: "windows_reset_wu_components",
    label: "Windows PS: Reset-WUComponents",
    description: "Resets update components/cache when update engine is stuck.",
    family: "windows_os_native",
    platform: "windows",
    shell: "powershell",
    shellOptions: ["powershell"],
    runAsSystem: true,
    command: "Reset-WUComponents -Verbose",
    tags: ["windows", "powershell", "windowsupdate", "reset"],
  },
  {
    id: "windows_add_microsoft_update",
    label: "Windows PS: Add-WUServiceManager -MicrosoftUpdate",
    description: "Enables Microsoft Update sources such as Office updates.",
    family: "windows_os_native",
    platform: "windows",
    shell: "powershell",
    shellOptions: ["powershell"],
    runAsSystem: true,
    command: "Add-WUServiceManager -MicrosoftUpdate",
    tags: ["windows", "powershell", "windowsupdate", "service-manager"],
  },
  {
    id: "windows_hide_kb",
    label: "Windows PS: Hide-WUUpdate -KBArticleID",
    description: "Blocks a specific problematic KB from installing.",
    family: "windows_os_native",
    platform: "windows",
    shell: "powershell",
    shellOptions: ["powershell"],
    runAsSystem: true,
    command: "Hide-WUUpdate -KBArticleID KB5030219",
    tags: ["windows", "powershell", "windowsupdate", "hide", "kb"],
  },
  {
    id: "windows_remove_kb",
    label: "Windows PS: Remove-WindowsUpdate -KBArticleID",
    description: "Uninstalls a specific KB package.",
    family: "windows_os_native",
    platform: "windows",
    shell: "powershell",
    shellOptions: ["powershell"],
    runAsSystem: true,
    command: "Remove-WindowsUpdate -KBArticleID KB5030219",
    tags: ["windows", "powershell", "windowsupdate", "remove", "kb"],
  },
  {
    id: "windows_winget_upgrade_all",
    label: "Windows: winget upgrade --all",
    description: "Updates all packages installed via Winget.",
    family: "windows_app_updates",
    platform: "windows",
    shell: "powershell",
    shellOptions: ["powershell", "cmd"],
    runAsSystem: false,
    command: "winget upgrade --all --accept-package-agreements --accept-source-agreements",
    tags: ["windows", "winget", "upgrade", "apps"],
  },
  {
    id: "windows_winget_list_upgrades",
    label: "Windows: winget list --upgrade-available",
    description: "Lists only Winget-managed apps that have updates.",
    family: "windows_app_updates",
    platform: "windows",
    shell: "powershell",
    shellOptions: ["powershell", "cmd"],
    runAsSystem: false,
    command: "winget list --upgrade-available",
    tags: ["windows", "winget", "list", "updates"],
  },
  {
    id: "windows_choco_upgrade_all",
    label: "Windows: choco upgrade all -y",
    description: "Updates all Chocolatey-managed packages.",
    family: "windows_app_updates",
    platform: "windows",
    shell: "powershell",
    shellOptions: ["powershell", "cmd"],
    runAsSystem: true,
    command: "choco upgrade all -y",
    tags: ["windows", "chocolatey", "choco", "upgrade"],
  },
  {
    id: "windows_scoop_update_all",
    label: "Windows: scoop update *",
    description: "Updates all Scoop-managed packages.",
    family: "windows_app_updates",
    platform: "windows",
    shell: "powershell",
    shellOptions: ["powershell", "cmd"],
    runAsSystem: false,
    command: "scoop update *",
    tags: ["windows", "scoop", "update", "apps"],
  },
  {
    id: "windows_dism_get_packages",
    label: "Windows: dism /online /get-packages",
    description: "Lists OS packages and feature updates using DISM.",
    family: "windows_app_updates",
    platform: "windows",
    shell: "powershell",
    shellOptions: ["powershell", "cmd"],
    runAsSystem: true,
    command: "dism /online /get-packages",
    tags: ["windows", "dism", "packages", "os"],
  },
];

export const MIN_COMMAND_MATRIX_BUNDLES = [
  {
    id: "linux_package_management_full",
    label: "Linux Package Management (Full Matrix)",
    description: "Complete Linux package-management command matrix for update, cleanup, and verification.",
    platform: "linux",
    commandIds: [
      "linux_apt_update",
      "linux_apt_upgrade",
      "linux_apt_full_upgrade",
      "linux_apt_autoremove",
      "linux_dnf_upgrade",
      "linux_yum_update",
      "linux_pacman_update",
      "linux_zypper_update",
      "linux_list_upgradable",
      "linux_kernel_version",
    ],
  },
  {
    id: "linux_patch_cycle",
    label: "Linux Patch Cycle (Apt Focused)",
    description: "Ubuntu/Debian patch cycle with verification checks.",
    platform: "linux",
    commandIds: [
      "linux_patch_cycle",
      "linux_list_upgradable",
      "linux_kernel_version",
    ],
  },
  {
    id: "windows_os_native_full",
    label: "Windows OS + Native Tools (Full Matrix)",
    description: "Complete Windows OS and PSWindowsUpdate command matrix.",
    platform: "windows",
    commandIds: [
      "windows_usoclient_scan",
      "windows_usoclient_download",
      "windows_usoclient_install",
      "windows_usoclient_restart",
      "windows_wuauclt_detectnow",
      "windows_wuauclt_updatenow",
      "windows_get_hotfix",
      "windows_get_wu_reboot_status",
      "windows_get_windows_update",
      "windows_install_windows_update",
      "windows_get_wu_history",
      "windows_reset_wu_components",
      "windows_add_microsoft_update",
      "windows_hide_kb",
      "windows_remove_kb",
    ],
  },
  {
    id: "windows_app_updates_full",
    label: "Windows App + Third-Party Updates (Full Matrix)",
    description: "Winget/Chocolatey/Scoop plus DISM package inventory.",
    platform: "windows",
    commandIds: [
      "windows_winget_upgrade_all",
      "windows_winget_list_upgrades",
      "windows_choco_upgrade_all",
      "windows_scoop_update_all",
      "windows_dism_get_packages",
    ],
  },
  {
    id: "windows_patch_cycle",
    label: "Windows Patch Cycle (Scan to Install)",
    description: "Recommended Windows patch flow from discovery to post-install evidence.",
    platform: "windows",
    commandIds: [
      "windows_usoclient_scan",
      "windows_usoclient_download",
      "windows_usoclient_install",
      "windows_get_hotfix",
      "windows_get_wu_reboot_status",
      "windows_get_wu_history",
    ],
  },
];

const COMMAND_BY_ID = new Map(MIN_COMMAND_MATRIX.map((item) => [item.id, item]));
const BUNDLE_BY_ID = new Map(MIN_COMMAND_MATRIX_BUNDLES.map((item) => [item.id, item]));

const toPlatform = (value) => {
  const raw = String(value || "").trim().toLowerCase();
  if (raw === "windows" || raw === "linux") return raw;
  return "all";
};

export const getMatrixCommandById = (id) => COMMAND_BY_ID.get(String(id || "").trim()) || null;

export const getMatrixBundleById = (id) => BUNDLE_BY_ID.get(String(id || "").trim()) || null;

export const resolveMatrixBundleCommands = (bundleId) => {
  const bundle = getMatrixBundleById(bundleId);
  if (!bundle) return [];
  return (bundle.commandIds || [])
    .map((id) => getMatrixCommandById(id))
    .filter(Boolean);
};

export const filterMatrixCommands = (items = MIN_COMMAND_MATRIX, options = {}) => {
  const list = Array.isArray(items) ? items : [];
  const query = String(options.query || "").trim().toLowerCase();
  const platform = toPlatform(options.platform);
  return list.filter((item) => {
    if (!item || typeof item !== "object") return false;
    if (platform !== "all" && String(item.platform || "").toLowerCase() !== platform) return false;
    if (!query) return true;
    const blob = [
      item.id,
      item.label,
      item.description,
      item.family,
      item.command,
      ...(Array.isArray(item.tags) ? item.tags : []),
    ]
      .join(" ")
      .toLowerCase();
    return blob.includes(query);
  });
};

export const commandMatrixToPlaybookStep = (command, index = 1) => {
  const row = command && typeof command === "object" ? command : {};
  const id = String(row.id || `matrix_step_${index}`).replace(/[^a-zA-Z0-9_-]/g, "_");
  const label = String(row.label || row.id || "Matrix Command").trim();
  return {
    id: `step_${index}_${id}`,
    action: "global-shell",
    args: {
      command: String(row.command || "").trim(),
      run_as_system: row.runAsSystem ? "true" : "false",
    },
    reason: `Matrix command: ${label}`,
  };
};

export const buildMatrixPlaybookDraft = (bundleId) => {
  const bundle = getMatrixBundleById(bundleId);
  if (!bundle) return null;
  const commands = resolveMatrixBundleCommands(bundle.id);
  if (!commands.length) return null;
  return {
    name: `matrix-${bundle.id}`,
    description: bundle.description || "Command matrix playbook template",
    source: {
      mode: "matrix",
      bundle_id: bundle.id,
      platform: bundle.platform || "all",
    },
    steps: commands.map((command, index) => commandMatrixToPlaybookStep(command, index + 1)),
  };
};
